-   id: yam
    name: Format yaml properly using yam
    description: Helps to prevent any linting check failures in CI 
    entry: yam
    language: golang
    stages: [pre-commit, manual]
    types: [yaml]
