# Copyright 2025 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

issuer: https://token.actions.githubusercontent.com
subject: repo:chainguard-dev/yam:ref:refs/heads/main
claim_pattern:
  job_workflow_ref: chainguard-dev/yam/.github/workflows/release.yaml@refs/heads/main

# the release workflow needs write permissions to create and push tags
permissions:
  contents: write
